### ISSUE TITLE
CommandNode with response output => secondary output is fired if a different command is received

### ISSUE THREAD

**Issue by daevidpreis** [windkh/node-red-contrib-telegrambot#115]
The secondary output of a command node is fired if a different command is received. So this "different" command is handled by the node with response output and the command node that's configured for that command.

Try the example. First fire command /one, than command /two. The seconds command is handled by both nodes.

```
[{"id":"16d6a09c.80311f","type":"telegram command","z":"5ee6bd01.28faa4","name":"","command":"/one","bot":"e84499ee.ca03c8","strict":false,"hasresponse":true,"x":1830,"y":3900,"wires":[[],["174f2a68.8ab216"]]},{"id":"d1bd9122.6388c","type":"telegram command","z":"5ee6bd01.28faa4","name":"","command":"/two","bot":"e84499ee.ca03c8","strict":false,"hasresponse":true,"x":1830,"y":3960,"wires":[["f38b47dd.7d8c78"],[]]},{"id":"174f2a68.8ab216","type":"debug","z":"5ee6bd01.28faa4","name":"cmd one => secondary output","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":2040,"y":3900,"wires":[]},{"id":"f38b47dd.7d8c78","type":"debug","z":"5ee6bd01.28faa4","name":"cmd two => first output","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":2010,"y":3960,"wires":[]},{"id":"e84499ee.ca03c8","type":"telegram bot","z":"","botname":"Dummy Bot","usernames":"","chatids":"","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false}]
```

**Comment by windkh** [comment]
Ich schaus mal an ... danke

**Comment by daevidpreis** [comment]
PR mit Fix & 2 neuen Features kommt gleich

**Comment by windkh** [comment]
Da kam über die Zeit so viel Zeug dazu ... kann schon sein dass da was durchgerutscht ist

**Comment by windkh** [comment]
Fixed in version 8.3.1

**Comment by Barabba11** [comment]
can somebody kindly explain me how it works?
"The second output is only issued if a command was received before. If another ocmmand was triggered in the meantime the pending status of the first one is reset."

what exactly is the meantime? now to reset the pending status of the first command? 
Thank you

**Comment by windkh** [comment]
If your bot receives a command and returns a inlinekeyboard or any other question to the user then your bot needs to process the user‘s response. This respone is sent to output 2.

**Comment by Barabba11** [comment]
Ok I got it, thanks, to tell that with my words (if may can help someone) the goal is to semplify the user asking him to choose between 2 answers, by pressing buttons. Only on this case the second output is used, and it cotain the answer (while the first output was cotaining the question).
About the variable context.global.keyboard = {pending:true}; ho this is useful for? Is it useful for me to remember there is a pending question and I should not allow a second command (which pretend an answer too) because I'll lose the first question, or because the modult will check this variable and preventing itself to do something?
As the app in the phone can't be used when triggered a question should we consider a second question coming from another device.. or because the main devices for example reboot before answer?
 _If another ocmmand was triggered in the meantime the pending status of the first one is reset_means the question asked become forbidden? (and nothing will be sent on outputs?) It looks the case for 2 phones, the forst send the question but take much time to answer, by this time the second mobile ask for another question. Now we should suppose that the when the first phone answers there will be not produced nothing, this is why we need to check  context.global.keyboard forst of all, before send a question?

**Comment by windkh** [comment]
The former example used the flow context to store the messageId ... this is not sufficient for a real bot. For that reason storing the state per user and chat is implemented inside the command node itsrlf

**Comment by Barabba11** [comment]
Thanks for help, I'm getting a bit confused now, "implemented inside the command node itsrlf" what does it mean? I think I need to clear my questions before to understand more..
Thanks

**Comment by windkh** [comment]
... the command node stores the user amd the chat id if a command was received.
If the user from the stored chat answers output 2 is issued
