### ISSUE TITLE
Formatting Text

### ISSUE THREAD

**Issue by beeryben** [windkh/node-red-contrib-telegrambot#128]
I wasn't able to send the text as monotext. Is this supported? If it is could you point me in the right direction?

The way that I've seen it most commonly done is by placing a back-tick on both sides of the text (`text`)

**Comment by windkh** [comment]
Maybe MarkdownV2 as parse mode helps:

`

mentioned.
MarkdownV2 style

To use this mode, pass MarkdownV2 in the parse_mode field. Use the following syntax in your message:

*bold \*text*
_italic \*text_
__underline__
~strikethrough~
*bold _italic bold ~italic bold strikethrough~ __underline italic bold___ bold*
[inline URL](http://www.example.com/)
[inline mention of a user](tg://user?id=123456789)
`inline fixed-width code`
```
pre-formatted fixed-width code block
```
```python
pre-formatted fixed-width code block written in the Python programming language
```
Please note:

Any character with code between 1 and 126 inclusively can be escaped anywhere with a preceding '\' character, in which case it is treated as an ordinary character and not a part of the markup.
Inside pre and code entities, all '`' and '\' characters must be escaped with a preceding '\' character.
Inside (...) part of inline link definition, all ')' and '\' must be escaped with a preceding '\' character.
In all other places characters '_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!' must be escaped with the preceding character '\'.
In case of ambiguity between italic and underline entities __ is always greadily treated from left to right as beginning or end of underline entity, so instead of ___italic underline___ use ___italic underline_\r__, where \r is a character with code 13, which will be ignored.

`

**Comment by beeryben** [comment]
Thanks for the tip.

I'm having issues with parse_mode. I tried Markdown and MarkdownV2
   msg.payload.options = {parse_mode : "Markdown"};

I can see that the parse_mode option makes it to the debug node but nothing makes it back to telegram. When comment out that particular line everything starts working again

To make sure that it wasn't something to do with msg.payload.options I tried another example from your code snippets. Adding this line in didn't prevent the return message in telegram like parse_mode did.
   msg.payload.options = {disable_web_page_preview : true};

I also upgraded to the latest version to ensure that wasn't the issue but it didn't help.

Is there something that I'm missing?

**Comment by windkh** [comment]
Let me try this out by myself....

**Comment by windkh** [comment]
I tried it by myself:

in a function node I created a message like:
`
msg.payload.options = {parse_mode : "MarkdownV2"};
msg.payload.content = "*bold \\*text* \n"+
"_italic \\*text_\n"+
"__underline__\n"+
"~strikethrough~\n"+
"*bold _italic bold ~italic bold strikethrough~ __underline italic bold___ bold*\n"+
"[inline URL](http://www.example.com/)\n"+
"[inline mention of a user](tg://user?id=123456789)\n"+
"`inline fixed-width code`\n"+
"```\n"+
"pre-formatted fixed-width code block\n"+
"```\n"+
"```python\n"+
"pre-formatted fixed-width code block written in the Python programming language\n"+
"```";
return msg;
`

Then  the output looked like:
![image](https://user-images.githubusercontent.com/10910767/92324724-a2eb6680-f044-11ea-9162-4213861aadac.png)

**Comment by windkh** [comment]
I hope that helps
