### ISSUE TITLE
Multiple webhook with same local bot IP

### ISSUE THREAD

**Issue by mineus55** [windkh/node-red-contrib-telegrambot#167]
Hi. Is it doable?

Currently, when I tried to setup more than 1 webhook using the same local bot IP, NR crashes into an infinite restart loop. This is the source of the crash:
EADDRINUSE: address already in use 0.0.0.0:8443

Obviously the 2nd webhook is trying to listen on already used port...and using a different port got rid of this error...but I was hoping to keep using the same port...is it possible?

**Comment by windkh** [comment]
You mean that you want to run two different bots using the same local ip and port? That won‘t work.Choose a different port for the second bot.Gesendet mit der WEB.DE iPad AppAm 04.04.21 um 16:50 schrieb mineus55
                
            
            
                
                    Von: "mineus55" ***@***.***>Datum: 4. April 2021An: "windkh/node-red-contrib-telegrambot" ***@***.***>Cc: "Subscribed" ***@***.***>Betreff: [windkh/node-red-contrib-telegrambot] Multiple webhook with same local bot IP (#167)
                
                
Hi. Is it doable?
Currently, when I tried to setup more than 1 webhook using the same local bot IP, NR crashes into an infinite restart loop. This is the source of the crash:
EADDRINUSE: address already in use 0.0.0.0:8443
Obviously the 2nd webhook is trying to listen on already used port...and using a different port got rid of this error...but I was hoping to keep using the same port...is it possible?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/windkh/node-red-contrib-telegrambot/issues/167",
"url": "https://github.com/windkh/node-red-contrib-telegrambot/issues/167",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
