### ISSUE TITLE
Add support for Live Locations

### ISSUE THREAD

**Issue by windkh** [windkh/node-red-contrib-telegrambot#46]
see also 
https://github.com/yagop/node-telegram-bot-api/issues/438

**Comment by opep** [comment]
In the above link there is an.information: "Live Locations supported in v0.30.0.".
I could capture in node-red the location when sharing CURRENT LOCATION, when only one location is sent. 
When Sharing My Live Location, no location is.captured. What could be.wrong? Since Telegrambot seems to support it..
Any help is welcome. Thanks.

**Comment by windkh** [comment]
Some functions need to be implemented first, so that the nodes will call the required functions of the underlying lib... be patient

**Comment by opep** [comment]
Thanks for your feedback. I asked because the link said it was implemented and I could be doing something wrong. Anyway I'm glad that it is planned. Keep the good work. Thanks.

**Comment by windkh** [comment]
Version 4.2.0 support sending a and editing a live location.
I discovered the same problem when receiving live locations. I sent a live location using my smart phone, but only received the initial location. :(

**Comment by windkh** [comment]
Version 4.3.0 contains an example for receiving live location updates
