### ISSUE TITLE
Receive image

### ISSUE THREAD

**Issue by RogierQ** [windkh/node-red-contrib-telegrambot#56]
Hi!

I have been trying many time to receive an image that has ben send to the bot from a mobile device.
But i cannot get it working.
Is there an example available to do this?

Thanks
Rogier

**Comment by nolimits2k** [comment]
Hi, I´ve got the exact same issue, tried multiple variations. This is my actual flow:

![flow](https://user-images.githubusercontent.com/40544473/47045448-1eaf4200-d193-11e8-84ad-b959520b164e.png)

Code in "Build Message 1":
msg.payload = {chatId : <# of my chatID>, type: "photo", content: 'http://192.168.2.90:10090/cam1.jpg' }
return msg;

type: "message" works btw...

**Comment by windkh** [comment]
@nolimits2k 
There is an example that should work for a file which is present on the local harddisk:
https://github.com/windkh/node-red-contrib-telegrambot/blob/master/examples/sendphoto.json

Though the bot api documenation states that also an HTTP URL should work I have not tried this before
(https://core.telegram.org/bots/api#sendphoto). 
I think that that URL must be a public one available in the internet, so that the telegram server is able to download the image from there and pass it on to the destination. If you want to get this scenario running I would download the file from 192.168.2.90 and send this local file e.g. "c:/temp/cam1.jpg"

**Comment by windkh** [comment]
For a better understanding on receiving files please read also this:
https://github.com/windkh/node-red-contrib-telegrambot/issues/38

**Comment by nolimits2k** [comment]
Thanks for your quick reply - will give it a try.

**Comment by nolimits2k** [comment]
Thanks @windkh - saved as binary to disk and used that jpg - now it works :-)

**Comment by windkh** [comment]
@nolimits2k perfect, but I guess that was not the same problem as @RogierQ  had, or?

**Comment by nolimits2k** [comment]
btw any chance to submit multiple chatId´s with one msg.payload?

**Comment by windkh** [comment]
Sorry, not at the moment ... but could be a new feature. I will put it on my list.

**Comment by RogierQ** [comment]
Sure! Thanks for replying so quickly.
I have a working setup wich sends and receives messages.
When i send an image and connect a debug node to the receive node i get nothing in the debug screen.

The image is send from my iphone.

**Comment by windkh** [comment]
Can you send me your flow?

**Comment by RogierQ** [comment]
sure, its not that big, just try to receive image
`[{"id":"d72c41fd.2b5e1","type":"telegram receiver","z":"7f565aeb.330b84","name":"","bot":"27e7473a.85bf","saveDataDir":"","x":387.5,"y":412,"wires":[["2c1679ce.99ed5e"],["2c1679ce.99ed5e"]]},{"id":"2c1679ce.99ed5e","type":"debug","z":"7f565aeb.330b84","name":"","active":true,"console":"false","complete":"false","x":645,"y":410,"wires":[]},{"id":"27e7473a.85bf","type":"telegram bot","z":"","botname":"botname","usernames":"username","chatids":"12345566"}]`

**Comment by RogierQ** [comment]
just updated the node ;-)
now it receives the weblink and thing.
so it works!
now need to find out how to save the image

**Comment by windkh** [comment]
You can configure a dir in the config node where data is stored
