### ISSUE TITLE
commands getting delayed

### ISSUE THREAD

**Issue by qwertangel** [windkh/node-red-contrib-telegrambot#74]
There are several times when the command node gets the command with delay as long as up to 2 minutes. It works fine sometimes but other times it takes long time for node to get message. I have high speed internet and double checked that there is no issue with internet at that time. I also checked that node is in 'connected' state. Any ideas what else I should be looking at ?

**Comment by windkh** [comment]
Hi ... never had that kind of issue. How often do you get this? Do you make use of the polling mode or webhook?

**Comment by windkh** [comment]
not reproducable

**Comment by GerardWassink** [comment]
I experience similar problems. See this [thread on the Node-red forum](https://discourse.nodered.org/t/intermittent-behavior-of-telegram-bot/13367). How can we work together to solve this?

Gerard Wassink

**Comment by windkh** [comment]
Hm if you can reproduce it then maybe there is a chance to find it... we could do a webmeeting together... but not right now as I am at work

**Comment by GerardWassink** [comment]
Where are you located? (time-zone wise) I'm in the Netherlands.

**Comment by windkh** [comment]
Germany

**Comment by GerardWassink** [comment]
That should be compatible then. Tomorrow? (time?).

**Comment by GerardWassink** [comment]
I think I may have found it. When I open one of my four command nodes, i can choose the bot name. When I open the drop-down list I see three bots with the same name; presumably because early in the process I've been heaviliy testing... The two commands that where working made use of the second of the three choices (again: with the same name. The other ones used the third entry. I changed the last two now so they make use of the second bot-choice.

Up until now they have not missed a beat!

Perhaps we can still look into it to determine what was the cause, so as to help others?

Gerard

**Comment by windkh** [comment]
That makes sense! Hm I wonder how to avoid having two or mire config nodes polling for the same token. 

Thanks alot for pointing this out!

**Comment by TotallyInformation** [comment]
The easiest way to avoid this is to create an admin REST API. Keep track of each bot id as it is created via a new node instance and use an API to deliver the list so that your admin panel can check for it when a user is editing the settings.

This is what I do with uibuilder v2 to try to ensure that URL's remain unique.

**Comment by GerardWassink** [comment]
Will you let us know Julian, when you found a solution?

**Comment by windkh** [comment]
> The easiest way to avoid this is to create an admin REST API. Keep track of each bot id as it is created via a new node instance and use an API to deliver the list so that your admin panel can check for it when a user is editing the settings.
> 
> This is what I do with uibuilder v2 to try to ensure that URL's remain unique.

Hm... I know what you mean... I will have a look at your implementation. Thanks!
